name: Deploy CI/CD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
          token: ${{secrets.GITHUB_TOKEN}}
          cache-dependency-path: /home/ubuntu/cicdtest
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements'
      - name: Deploy to EC2
        uses: appleboy/ssh-action@main
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/cicdtest
            git pull
            sudo pip install -r requirements
            sudo systemctl daemon-reload
            sudo systemctl restart cicdapp.service
